version-file = "VERSION"

[hooks]
pre-commit = [
    "revive --config=.revive.toml --formatter=stylish",
    "husky lint-staged",
]

commit-msg = ["husky lint-commit"]

[lint-staged]
"*.go" = ["goimports -l -w", "gofmt -l -w"]

[lint-commit]
types = "^(feat|fix|chore|ci|docs|perf|refactor|revert|style|test)$"
header = "^(?P<type>\\w+)(\\((?P<scope>[\\w/.-]+)\\))?(?P<breaking>!)?:( +)?(?P<header>.+)"
