ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 0

enableAllRules = true

[rule.function-result-limit]
arguments = [2]

[rule.banned-characters]
disabled = true

[rule.cognitive-complexity]
arguments = [7]

[rule.cyclomatic]
arguments = [10]

[rule.max-public-structs]
disabled = true

[rule.function-length]
disabled = true

[rule.file-header]
disabled = true

[rule.line-length-limit]
arguments = [100]

[rule.argument-limit]
disabled = true

[rule.package-comments]
severity = "error"
Exclude = ["internal/**/*.go", "**/*.pb.go", "TEST"]

[directive.specify-disable-reason]
severity = "error"
